[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
solc = "0.8.26"
optimizer = true
optimizer_runs = 200
via_ir = false
ffi = false
fs_permissions = [{ access = "read-write", path = "./"}]

[profile.remappings]
"@openzeppelin/contracts/" = "lib/openzeppelin-contracts/contracts/"
"forge-std/" = "lib/forge-std/src/"

[rpc_endpoints]
mainnet = "https://rpc.ankr.com/eth"
polygon = "https://rpc.ankr.com/polygon"
